[output]
path = "output"

[output.csv]
name = "output.csv"

[output.geom]
name1 = "spatial.gpkg"

[vulnerability]
file = "./vulnerability/vulnerability_curves.csv"
unit = "feet"

[exposure.csv]
file = "./exposure/exposure.csv"

[exposure.geom]
crs = "EPSG:4326"
file1 = "./exposure/exposure.gpkg"
file2 = "./exposure/exposure1.gpkg"
unit = "feet"

[hazard]
return_periods = "None"
file = "hazard\\hazard_map.nc"
crs = "EPSG:26917"
elevation_reference = "datum"
risk = false

[hazard.settings]
subset = "hazard_map"
var_as_band = false
